const products = [
  {
    _id: '1',
    name: 'Apple iPhone 13 128GB Đỏ',
    image: '/images/13-do.jpg',
    description:
      'Điểm thay đổi lớn trên 13 Pro Max có thể là phần nhô của cụm camera. Trong khi đó mặt trước của thiết bị được phủ một lớp Ceramic Shield, loại vật liệu cứng hơn bất kỳ loại kính điện thoại thông minh nào hiện có trên thị trường, giúp bảo vệ màn hình iPhone hiệu quả.',
    brand: 'Apple',
    category: 'mobile phone',
    price: 1200,
    countInStock: 20,
    rating: 4.9,
    numReviews: 18,
  },
  {
    _id: '8',
    name: 'Apple iphone 8 Màu Vang',
    image: '/images/iPhone-8-plus-vang.png',
    description:
      'Điện thoại iPhone 8 mặc dù là phiên bản đã cũ nhưng hiệu năng vẫn thuộc loại mạnh nhất trên thị trường. Với vi xử lý A11 Bionic sáu nhân, RAM 3GB cùng bộ nhớ trong 64GB, chiếc điện thoại của Apple đáp ứng hoàn hảo mọi nhu cầu lưu trữ, làm việc lẫn giải trí với tốc độ nhanh đến kinh ngạc. Nếu nhu cầu lưu trữ của bạn cao hơn, có thể tham khảo iPhone 8 Plus 256GB cũ',
    brand: 'Apple',
    category: 'mobile phone',
    price: 499,
    countInStock: 10,
    rating: 4.5,
    numReviews: 11,
  },
  {
    _id: '3',
    name: 'Apple iPhone 12 Pro 128GB',
    image: '/images/thumb_IP12Pro_4.jpg',
    description:
      'Apple đã quyết định giữ nguyên thiết kế notch "tai thỏ" quen thuộc cho màn hình iPhone 12, nhưng phần notch đã được tinh giản nhỏ gọn lại nhằm tạo thêm tỷ lệ hiển thị hình ảnh trên màn hình. Về kích thước, màn hình của máy độ phân giải 2532x 1170pixels và có kích thước 6.1 inch, nhỏ hơn so với iPhone 12 Pro Max (6.7 inch)',
    brand: 'Apple',
    category: 'mobile phone',
    price: 950,
    countInStock: 17,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Apple iphone 8 Đỏ',
    image: '/images/iPhone-8-plus-do.png',
    description:
      'Điện thoại iPhone 8 mặc dù là phiên bản đã cũ nhưng hiệu năng vẫn thuộc loại mạnh nhất trên thị trường. Với vi xử lý A11 Bionic sáu nhân, RAM 3GB cùng bộ nhớ trong 64GB, chiếc điện thoại của Apple đáp ứng hoàn hảo mọi nhu cầu lưu trữ, làm việc lẫn giải trí với tốc độ nhanh đến kinh ngạc. Nếu nhu cầu lưu trữ của bạn cao hơn, có thể tham khảo iPhone 8 Plus 256GB cũ',
    brand: 'Apple',
    category: 'mobile phone',
    price:600,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Apple iPhone 11 128GB Tím',
    image: '/images/thumb_iP11_5.jpg',
    description:
      'Màu sắc phù hợp cá tính - 6 màu sắc bắt mắt để lựa chọn ,Hiệu năng mượt mà, ổn định - Chip A13, RAM 4GB ,Bắt trọn khung hình - Camera kép hỗ trợ góc rộng, chế độ Night Mode ,Yên tâm sử dụng - Kháng nước, kháng bụi IP68, kính cường lực Gorilla Glass',
    brand: 'Apple',
    category: 'mobile phone',
    price: 800,
    countInStock: 10,
    rating: 4.6,
    numReviews: 11,
  },
  {
    _id: '5',
    name: 'Apple iPhone 11 128GB Đen',
    image: '/images/thumb_iP11_2.jpg',
    description:
      'Màu sắc phù hợp cá tính - 6 màu sắc bắt mắt để lựa chọn ,Hiệu năng mượt mà, ổn định - Chip A13, RAM 4GB ,Bắt trọn khung hình - Camera kép hỗ trợ góc rộng, chế độ Night Mode ,Yên tâm sử dụng - Kháng nước, kháng bụi IP68, kính cường lực Gorilla Glass',
    brand: 'Apple',
    category: 'mobile phone',
    price: 810,
    countInStock: 10,
    rating: 4.6,
    numReviews: 41,
  },
  {
    _id: '21',
    name: 'Apple iPhone 11 128GB Đỏ',
    image: '/images/thumb_iP11_7.jpg',
    description:
      'Màu sắc phù hợp cá tính - 6 màu sắc bắt mắt để lựa chọn ,Hiệu năng mượt mà, ổn định - Chip A13, RAM 4GB ,Bắt trọn khung hình - Camera kép hỗ trợ góc rộng, chế độ Night Mode ,Yên tâm sử dụng - Kháng nước, kháng bụi IP68, kính cường lực Gorilla Glass',
    brand: 'Apple',
    category: 'mobile phone',
    price: 800,
    countInStock: 10,
    rating: 4.6,
    numReviews: 24,
  },
  {
    _id: '6',
    name: 'Apple iPhone 11 Vàng',
    image: '/images/thumb_iP11_6.jpg',
    description:
      'Màu sắc phù hợp cá tính - 6 màu sắc bắt mắt để lựa chọn ,Hiệu năng mượt mà, ổn định - Chip A13, RAM 4GB ,Bắt trọn khung hình - Camera kép hỗ trợ góc rộng, chế độ Night Mode ',
    brand: 'Apple',
    category: 'mobile phone',
    price: 825,
    countInStock: 10,
    rating: 4.6,
    numReviews: 101,
  },
  {
    _id: '11',
    name: 'SamSung  Headphones',
    image: '/images/600_tai-nghe-bluetooth-samsung-galaxy-buds.jpg',
    description:
      'Chống ồn chủ động ANC lọc mọi tạp âm của môi trường ,Chế độ xuyên âm cho phép nghe thấy giọng nói của người xung quanh ,Âm thanh 3D với loa 2 chiều (loa trầm 11mm,loa bổng 6.5mm) ,3 micro khử ồn hiệu quả ,Thiết kế hạt đậu ôm khít tai,không rơi khi vận động .Kháng nước IPX7,không lo vào nước khi tập luyện .Pin 5 giờ và 13 giờ khi dùng cùng hộp sạc',
    brand: 'Sam Sung',
    category: 'Electronics',
    price: 300,
    countInStock: 10,
    rating: 4.5,
    numReviews: 123,
  },
  {
    _id: '12',
    name: 'Apple Watch S6 SE GPS',
    image: '/images/thumb_S6-GPS_2.jpg',
    description:
      'Chức năng màn hình luôn bật giữ cho chức năng xem giờ luôn hoạt động,tiết kiệm pin hơn Thoải mái sử dụng ở hồ bơi hay ngoài trời với chuẩn kháng bụi IP6X ,chống nước đến 50m Đo nhịp tim,oxy trong máu,theo dõi giấc ngủ cùng nhiều tính năng sức khoẻ tích hợp sẵn ,Trải nghiệm âm nhạc với bộ nhớ trong 32GB cùng khả năng kết nối tai nghe bluetooth ,Cổng sạc Type C,sạc nhanh 45 phút cho 80% pin ,Hỗ trợ Esim cho phép nghe gọi ngay trên đồng hồ',
    brand: 'Apple',
    category: 'Watch',
    price: 702,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '13',
    name: 'Apple Watch SE GPS 2',
    image: '/images/thumb_SE-gps_2.jpg',
    description:
    'Chức năng màn hình luôn bật giữ cho chức năng xem giờ luôn hoạt động,tiết kiệm pin hơn Thoải mái sử dụng ở hồ bơi hay ngoài trời với chuẩn kháng bụi IP6X ,chống nước đến 50m Đo nhịp tim,oxy trong máu,theo dõi giấc ngủ cùng nhiều tính năng sức khoẻ tích hợp sẵn ,Trải nghiệm âm nhạc với bộ nhớ trong 32GB cùng khả năng kết nối tai nghe bluetooth ,Cổng sạc Type C,sạc nhanh 45 phút cho 80% pin ,Hỗ trợ Esim cho phép nghe gọi ngay trên đồng hồ',
    brand: 'Apple',
    category: 'Watch',
    price: 500,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '14',
    name: 'pple Watch SE GPS 3',
    image: '/images/thumb_SE-gps_3.jpg',
    description:
    'Chức năng màn hình luôn bật giữ cho chức năng xem giờ luôn hoạt động,tiết kiệm pin hơn Thoải mái sử dụng ở hồ bơi hay ngoài trời với chuẩn kháng bụi IP6X ,chống nước đến 50m Đo nhịp tim,oxy trong máu,theo dõi giấc ngủ cùng nhiều tính năng sức khoẻ tích hợp sẵn ,Trải nghiệm âm nhạc với bộ nhớ trong 32GB cùng khả năng kết nối tai nghe bluetooth ,Cổng sạc Type C,sạc nhanh 45 phút cho 80% pin ,Hỗ trợ Esim cho phép nghe gọi ngay trên đồng hồ',
    brand: 'Watch',
    category: 'Watch',
    price: 410,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '15',
    name: 'Sạc Dự Phòng',
    image: '/images/e314665d7c0115d5e3caec8c0acd0f6f.jpg',
    description:
      'Pin sạc dự phòng Energizer UE15032PQ được trang bị dung lượng lên đến 15000mAh một khoảng dung lượng đủ lớn để bạn sạc đầy điện thoại thông minh lên đến 4.5 lần',
    brand: 'Energizer',
    category: 'Electronics',
    price: 19,
    countInStock: 11,
    rating: 5,
    numReviews: 7,
  },
  {
    _id: '16',
    name: 'Vòng Đeo Tay Xiaomi',
    image: '/images/vong-deo-tay-thong-minh-xiaomi-mi-band-6-11.jpg',
    description:
      'Thiết kế nhỏ gọn,cảm giác đeo thoải mái ,Trang bị các tính năng theo dõi sức khoẻ như đo nhịp tim,chỉ số oxy trong máu,theo dõi giấc ngủ ,Thời lượng pin dài lên đến 15 ngày sử dụng,sạc đầy trong 1.5 giờ ,Tương thích với thiết bị Android 5.0 và iOS 10 trở lên ,Luyện tập mọi nơi với kháng nước 5ATM và 30 chế độ tập thể thao',
    brand: 'Xiaomi',
    category: 'Watch',
    price: 25,
    countInStock: 7,
    rating: 3.5,
    numReviews: 11,
  },
  {
    _id: '17',
    name: 'Sạc Dự Phòng Redmi',
    image: '/images/Redmi-Bank.jpg',
    description:
      'Pin sạc dự phòng Energizer UE15032PQ được trang bị dung lượng lên đến 15000mAh một khoảng dung lượng đủ lớn để bạn sạc đầy điện thoại thông minh lên đến 4.5 lần',
    brand: 'Redmi',
    category: 'Electronics',
    price: 56,
    countInStock: 0,
    rating: 4,
    numReviews: 4,
  },
  {
    _id: '18',
    name: 'Sạc Dự Phòng Xiaomi',
    image: '/images/Mi-bank.jpg',
    description:
      'Pin sạc dự phòng Energizer UE15032PQ được trang bị dung lượng lên đến 15000mAh một khoảng dung lượng đủ lớn để bạn sạc đầy điện thoại thông minh lên đến 4.5 lần',
    brand: 'Xiaomi',
    category: 'Electronics',
    price: 89,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '19',
    name: 'Apple Mac mini M1 16GB 256GB 2020',
    image: '/images/img-apple-main_1_1.jpg',
    description:
      'Apple Mac M1 sử dụng chip Apple M1 8 lõi kết hợp cùng với GPU 8 lõi và Neural Engine 16 lõi. Không những thế thiết bị còn sử dụng RAM hợp nhất 8GB. Giúp thiết bị có thể sử dụng với hiệu năng cao cho nhiều tác vụ',
    brand: 'Apple',
    category: 'Electronics',
    price: 1100,
    countInStock: 0,
    rating: 4,
    numReviews: 11,
  },
  {
    _id: '26',
    name: 'Apple iPhone 13 128GB Gold',
    image: '/images/13-pro-gold.jpg',
    description:
      'Điểm thay đổi lớn trên 13 Pro Max có thể là phần nhô của cụm camera. Trong khi đó mặt trước của thiết bị được phủ một lớp Ceramic Shield, loại vật liệu cứng hơn bất kỳ loại kính điện thoại thông minh nào hiện có trên thị trường, giúp bảo vệ màn hình iPhone hiệu quả.',
    brand: 'Apple',
    category: 'mobile phone',
    price: 1600,
    countInStock: 20,
    rating: 4.9,
    numReviews: 18,
  },
  {
    _id: '2',
    name: 'Apple iPhone 13 128GB Xanh',
    image: '/images/iphone-13-xanh.jpg',
    description:
      'Điểm thay đổi lớn trên 13 Pro Max có thể là phần nhô của cụm camera. Trong khi đó mặt trước của thiết bị được phủ một lớp Ceramic Shield, loại vật liệu cứng hơn bất kỳ loại kính điện thoại thông minh nào hiện có trên thị trường, giúp bảo vệ màn hình iPhone hiệu quả.',
    brand: 'Apple',
    category: 'mobile phone',
    price: 1540,
    countInStock: 20,
    rating: 4.9,
    numReviews: 18,
  },
  {
    _id: '9',
    name: 'Apple iPhone 13 128GB Hồng',
    image: '/images/iphone-13-hồng.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'mobile phone',
    price: 1500,
    countInStock: 10,
    rating: 4.5,
    numReviews: 11,
  },
  {
    _id: '20',
    name: 'Sạc nhanh Apple 20W ',
    image: '/images/thumb-1_1603689123.jpg',
    description:
      'Apple Mac M1 sử dụng chip Apple M1 8 lõi kết hợp cùng với GPU 8 lõi và Neural Engine 16 lõi. Không những thế thiết bị còn sử dụng RAM hợp nhất 8GB. Giúp thiết bị có thể sử dụng với hiệu năng cao cho nhiều tác vụ',
    brand: 'Apple',
    category: 'Electronics',
    price: 250,
    countInStock: 0,
    rating: 4,
    numReviews: 10,
  },
  {
    _id: '10',
    name: 'Airpods Wireless Bluetooth',
    image: '/images/apple-airpods.png',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electronics',
    price: 450,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
]

export default products
